"""Fixed typos

Revision ID: 1706cc38c502
Revises: 8f8f966a1374
Create Date: 2025-06-19 21:31:36.811037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1706cc38c502'
down_revision: Union[str, Sequence[str], None] = '8f8f966a1374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('party_time', sa.Time(), nullable=False))
    op.drop_column('party', 'part_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('part_time', sa.TIME(), nullable=False))
    op.drop_column('party', 'party_time')
    # ### end Alembic commands ###
